# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: emailapp.com
  secret_key_base: b9b2df20af7b0f45a8cc3521d526eeb9445a0fb75b7e5afd531d6ba65c1e40701a353324950dd8ee81fbd98dbbabb8d42db96bbdbfaf4ff6a6cebbbb8a9b1ce9

test:
  secret_key_base: 974ef8719a53b8dced97dd63c5668da8325e48390d60477268e13dc6e6d199279e6288240dee3ab36ff6a1986af9a9d024fee6e4e5fe8dc9fe8d181b2affe2af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
